version: '2' #docker-composeのバージョンを指定
services:
  dbserver:
    image: mysql:5.7
    ports:
      - "3316:3306"
    environment:
        MYSQL_DATABASE: ${SPRING_DATASOURCE_PASSWORD}
        MYSQL_ROOT_PASSWORD: ${SPRING_DATASOURCE_USERNAME}
    hostname: dbserver
    volumes:
      -  "./mysql:/docker-entrypoint-initdb.d"
  app:
    build: .
    volumes:
      - "./:/app"
    ports:
      - "8888:8080"
    links:
      - dbserver
    environment:
       SPRING_DATASOURCE_PASSWORD: ${SPRING_DATASOURCE_PASSWORD}
       SPRING_DATASOURCE_USERNAME: ${SPRING_DATASOURCE_USERNAME}