spring:
  datasource:
    url: jdbc:log4jdbc:mysql://localhost:3306/kotlin
     # mysql username & password
    driver-class-name: net.sf.log4jdbc.DriverSpy
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}
  jpa:
    database: mysql
logging:
  level:
    jdbc:
      sqltiming: DEBUG

