spring:
  datasource:
    url: jdbc:mysql://localhost:3306/kotlin
     # mysql username & password
    driver-class-name: com.mysql.jdbc.Driver
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}
  jpa:
    database: mysql
